## 1. NumPy Basics

>  ### Install NumPy

In [ ]:
pip install numpy

>  ### Creating Arrays

In [1]:
import numpy as np

array = np.array([23,34,45,56,65])
print(array)

[23 34 45 56 65]



> ### Array Attributes

In [2]:
arr = np.array(
                [[2,1,3,2],
                [3,4,5,6]]
            )

print(arr)
print(f"Array shape: {arr.shape}")
print(f"Array size: {arr.size}")
print(f"Array diamensions: {arr.ndim}")
print(f"Array elements type: {arr.dtype}")


[[2 1 3 2]
 [3 4 5 6]]
Array shape: (2, 4)
Array size: 8
Array diamensions: 2
Array elements type: int64
