<h1 style="color: #fffb00;
            font-size: 30px;
            font-weight: bold;
            font-family: Arial, sans-serif">NumPy Basics</h1>



<p style="color: #0088ff;
            font-size: 25px;
            font-weight: bold;
            font-family: Arial, sans-serif">🔹Install NumPY</p>

In [ ]:
pip install numpy



<p style="color: #0088ff;
            font-size: 25px;
            font-weight: bold;
            font-family: Arial, sans-serif">📘 Create Arrays</p>

In [24]:
import numpy as np

array = np.array([23,34,45,56,65])
print(array)

[23 34 45 56 65]



<p style="color: #0088ff;
            font-size: 25px;
            font-weight: bold;
            font-family: Arial, sans-serif">🔍 Array Attributes</p>

In [25]:
arr = np.array(
                [[2,1,3,2],
                [3,4,5,6]]
            )

print(arr)
print(f"Array shape: {arr.shape}")
print(f"Array size: {arr.size}")
print(f"Array diamensions: {arr.ndim}")
print(f"Array elements type: {arr.dtype}")


[[2 1 3 2]
 [3 4 5 6]]
Array shape: (2, 4)
Array size: 8
Array diamensions: 2
Array elements type: int64
